[package]
name = "rpc_server"
version = "0.0.1"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread"] }
tokio-tungstenite = { path = "../tungsten" }
amber_dchat_rpc_utils = { path = "../utils" }
futures-util = "0.3.30"
serde_json = "1.0.128"
